apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-server-cert
  namespace: argocd
spec:
  secretName: argocd-server-tls # Argo looks for this
  dnsNames:
    # TODO: Update with a domain and add to Kustomize
    - argocd.<your-domain>
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production # or your internal issuer
