---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-styles-cm
  namespace: argocd
data:
  custom-styles.css: |
    .sidebar {
      background: linear-gradient(to bottom, #999, #777, #333, #222, #111);
    }
