apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - argocd-server-cert.yaml
  # - argocd-ts-certs-cm.yaml
  # - argocd-ingress.yaml
  - argocd-cm.yaml
  # - argocd-rbac-cm.yaml
