apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payments-api
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    team: payments
    env: prod
spec:
  project: default
  source:
    repoURL: https://github.com/Cwagne17/payments-api.git # This is made up for example
    targetRevision: main
    path: deploy/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: payments
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
