apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - metrics-server-app.yaml
  - cert-manager-app.yaml
  - eso-app.yaml
  - gmsa-app.yaml
  - kyverno-app.yaml
  - argocd-config-app.yaml
